# Generated by Django 2.1.2 on 2018-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Poster')),
                ('start_time_and_date', models.DateTimeField(verbose_name='Event start time/date')),
                ('end_time_and_date', models.DateTimeField(verbose_name='Event end time/date')),
                ('location', models.CharField(max_length=255, verbose_name='Event location')),
                ('information', models.TextField(verbose_name='Event information')),
                ('food_provided', models.BooleanField(blank=True, verbose_name='Food Provided')),
                ('group_running', models.CharField(choices=[('RST', 'RST Event'), ('MSPT', 'Monash Sport Event'), ('MRS', 'Central MRS Event'), ('HS', 'Hall Society Event'), ('STO', 'RST ONLY EVENT')], default='RST', max_length=4)),
            ],
        ),
    ]
