# Generated by Django 2.1.2 on 2019-01-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('picture', models.ImageField(upload_to='RA_photos', verbose_name='picture')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='email')),
                ('facebook', models.CharField(blank=True, max_length=255, verbose_name='facebook')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='phone number')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('position', models.CharField(choices=[('CH', 'College Head'), ('DCH', 'Deputy College Head'), ('RSA', 'Residential Support Assistant'), ('RA', 'Resident Advisor')], default='RA', max_length=3)),
                ('wing', models.CharField(choices=[('1E', '1E'), ('1W', '1W'), ('2E', '2E'), ('2W', '2W'), ('3E', '3E'), ('3W', '3W'), ('4E', '4E'), ('4W', '4W'), ('GF', 'Ground Floor')], max_length=2)),
            ],
        ),
    ]
