# Generated by Django 2.1.2 on 2019-01-19 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_and_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('report_time', models.TimeField(verbose_name='Event Time')),
                ('first_floor', models.FloatField(verbose_name='1st Floor')),
                ('second_floor', models.FloatField(verbose_name='2nd Floor')),
                ('third_floor', models.FloatField(verbose_name='3rd Floor')),
                ('fourth_floor', models.FloatField(verbose_name='4th Floor')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
